### ISSUE TITLE
 how to implement 'python -m http.server' in 'python app.py' to d3.csv?

### ISSUE THREAD

**Issue by yongjinjiang** [yongjinjiang/EastAfrica-travel#1]
A=  having the line   <link rel="shortcut icon" href=""> in base.html and the file favicon.ico

without A,
d3.json can create table,  but can't get the json data from the route /registered_people 

with A,
  d3.json can't even create the table  

if we try d3.csv, it works if we use 'python -m http.server'. Is 'python -m http.server'.  allow  javascript to communicate with the serve? 
but how can we  implement 'python -m http.server' when we run python main.py?

**Comment by paulkaefer** [comment]
See examples [here](https://docs.python.org/3/library/http.server.html). `python -m http.server` allows you to implement a simple server via the command-line, whereas importing http.server will let you implement a web server in your code.

**Comment by yongjinjiang** [comment]
Thank you, Paul! That seems to be the solution to the issue.
